### ISSUE TITLE
Cannot train the model with provided codes

### ISSUE THREAD

**Issue by studyIR** [zhjy2016/SPLUT#8]
Hi. Thank you for your works and for sharing your codes.

I tried to train the model, but there is a problem with the provided codes.
![image](https://user-images.githubusercontent.com/122963871/213107436-06bfc82b-a84e-475f-829e-865a71851617.png)

In the training process, network shows around 7.6dB of AVG PSNR consistently as shown above.

Do I miss something for proper training? 

Thank you.

**Comment by zhjy2016** [comment]
I checked the relevant codes. The code in line 317 is deleted by error comment. You can cancel this comment or download the latest version of the code. Thanks for attention!

**Comment by studyIR** [comment]
> I checked the relevant codes. The code in line 317 is deleted by error comment. You can cancel this comment or download the latest version of the code. Thanks for attention!

Thank you for your quick response! It works now!
